@startuml ""
title Grid For Parent Flow

class App {
    +get_grid_for_parent()
}

class GridForParentController {
    +validate_grid_for_parent_details()
}

class GridForParentService {
    +process_grid_for_parent_details()
}

class DBConnection {
    +connect_db()
}

App --> GridForParentController
GridForParentController --> GridForParentService 
GridForParentService --> DBConnection

@enduml
