@startuml ""
title Grid For Studetnt Flow

class App {
    +get_grid_for_student()
}

class GridForStudentController {
    +validate_grid_for_student_details()
}

class GridForStudntService {
    +process_grid_for_student_details()
}

class DBConnection {
    +connect_db()
}

App --> GridForStudentController
GridForStudentController --> GridForStudntService 
GridForStudntService --> DBConnection

@enduml
