@startuml ""
title Insert Home Work Details 

class App {
    +insert_home_work_details()
}

class insertHomeWorkDetailsController {
    +validate_insert_home_work_details()
}

class insertHomeWorkDetailsService {
    +process_insert_home_work_details()
}

class DBConnection {
    +connect_db()
}

App --> insertHomeWorkDetailsController
insertHomeWorkDetailsController --> insertHomeWorkDetailsService 
insertHomeWorkDetailsService --> DBConnection

@enduml
