@startuml ""
title Search History

class App {
    +get_search_history()
}

class getSearchHistoryController {
    +validate_get_search_history()
}

class getSearchHistoryService {
    +process_get_search_history()
}

class DBConnection {
    +connect_db()
}

App --> getSearchHistoryController
getSearchHistoryController --> getSearchHistoryService 
getSearchHistoryService --> DBConnection

@enduml
